### ISSUE TITLE
Do not list python packages in plugin_dependencies in metadata.txt

### ISSUE THREAD

**Issue by nicogodet** [LostInZoom/cartagen-qgis#1]
https://github.com/LostInZoom/cartagen-qgis/blob/main/metadata.txt#L39
This line is meant to list QGIS plugins, not python package.

Ref: https://docs.qgis.org/3.34/en/docs/pyqgis_developer_cookbook/plugins/plugins.html#metadata-txt

**Comment by jberli** [comment]
Thanks for the correction, I'll fix that and submit an other version.
